Added smoke test to ci.yml with dummy DB

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -27,3 +27,19 @@ jobs:
         working-directory: .
         run: |
           docker buildx bake -f docker-compose.prod.yml --push
+
+  smoke-test-cd:
+    runs-on: ubuntu-latest
+    needs: build-push  # Only runs if build-push succeeds
+
+    steps:
+      - name: Run smoke test on production
+        run: |
+          URL="http://4.225.161.111/"
+          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
+          if [ $HTTP_STATUS -eq 200 ]; then
+            echo "✅ CD Smoke test passed (status: $HTTP_STATUS)"
+          else
+            echo "❌ CD Smoke test failed (status: $HTTP_STATUS)"
+            exit 1
+          fi
